<?php $yoda = array(
	'Difficult to see. Always in motion is the future.',
	'A Jedi craves not these things.',
	'Try not. Do, or do not. There is no try.',
	'Much to learn you still have, my old padawan.',
	'Not if anything to say about it I have.',
	'That is why you fail.',
	'No. There is another.',
	'Agree with you, the council does.',
	'Already know you that which you need.',
	'Grave danger you are in.',
	'Impatient you are.',
	'Patience! For the Jedi it is time to eat as well. Eat, eat.',
	'Concentrate... Feel the Force flow. Yes. Good. Calm, yes.',
	'Through the Force, things you will see.',
	'Always with you what cannot be done.',
	'Named must your fear be before banish it you can.',
	'The dark side I sense in you.',
	'Dwell on the could haves we must not.',
	'Focus on the solution we must.',
	'Hmm. That face you make. Look I so old to young eyes?',
	'You are reckless!',
	'No, no, there is no why.',
	'Nothing more will I teach you today.',
	'Much anger in this one.',
	'Unless... an elaborate distraction.',
	'Clear your mind of questions.',
	'Much to learn, you still have.',
	'But you do! Revealed, your opinion is.',
	'Strong am I with the Force, but not that strong.',
	'Always two there are, a master and an apprentice.',
	'Hmm. Control, control. You must learn control.',
	'Powerful you have become, the dark side I sense in you.',
	'Once you start down the dark path, forever will it dominate your destiny, consume you it will.',
	'A puppet am I, from beath the floor a man does control me. Yeees.',
	'When 900 years you reach, look as good, you will not.',
	'Beware of the dark side.',
	'You will know when you are calm, at peace. Passive. A Jedi uses the Force for knowledge and defense, never for attack.',
	'You must unlearn what you have learned.',
	'Fear is the path to the dark side. Fear leads to anger. Anger leads to hate. Hate leads to suffering.',
	'Is the future you see.'
); ?>