<?php $numbers = array(
	array('The loneliest number.', '1'),
	array('The meaning of life.', '42'),
	array('Elite', '1337'),
	array('The luckiest number.', '7'),
	array('How do you write boobs on a calculator?', '80085'),
	array('HAL', '9000'),
	array('The number of the beast.', '666'),
	array('How much did Romans pay for a CD?', '400'),
	array('When does the flux capacitor kick in?', '88'),
	array('How many years did Marylin itch?', '7'),
	array('Time to get high.', '420'),
	array('Sheldon\'s favorite number.','73'),
	array('He asked for a 13.', '31'),
	array('Through what port number are you playing this game?', '80'),
	array('The first perfect number.', '6'),
	array('The story of the secret star system.', '5555'),
	array('For God so loved the world, that He gave His only begotten Son, that whosoever believeth in Him should not perish, but have everlasting life.', '3:16'),
	array('A certain shade of green.', '2012'),
	array('Who is the king of time?', '3:13'),
	array('Girlfriend\'s age? My IQ? You must pay?', '55'),
	array('How can you make 30 into a dirty number?', 'xxx'),
	array('A slice of pie.', '3.14'),
	array('Two mouthfuls.', '69')
); ?>